<a href="https://colab.research.google.com/github/Amrinnridegreecollege/Python-mini-project-/blob/main/Interdution_Numpy_basic2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Numpy_ Numeric python
#Most powerful package_ library
#Numpy_ Dimrnsions
#A_oneDimensional Array
#[A,B]||[A
#        B]_Two Dimensoinal Array_Row||Column
#Three Dimensional
#Array _storing,Manipulating,similar Datatype
#Faster than any mathrmatical functions
#cinviniemt compared to other packages
#Memory efficiency
#support multi dimensional arrays

In [ ]:
#Install numpy_pip3 install numpy||pip install numpy

In [ ]:
import numpy as np

In [ ]:
#create a numpy array
#1D array
arr1D = np.array([1,2,3,4,5])
print (arr1D)

[1 2 3 4 5]


In [ ]:
#cteating 2D array _Matrix
arr2D = np.array ([
    [1,2,3],[4,5,6]
])

In [ ]:
print (arr2D)

[[1 2 3]
 [4 5 6]]


In [ ]:
#creating array with default values
#creating  matrix will all values of elements as"0"
allzeros=np.zeros((2,3))
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating  matrixwith all values of elements as'1'
allones=np.ones((2,3))
print( allones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with all values of elements as'constant value_n~Fill value '
allconstant=np.full((2,3),6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create an identity matrix_I_square matrux
identity=np.eye(4)
print (identity)
#Identity Matrix_Aii=1&Aij=0
#For all A Belongs to R MXN
#Aij_

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating a random Matrices

#between 0 and 1
rand1=np.random.rand (3,3)

In [ ]:
print(rand1)

[[0.03453505 0.40023537 0.47490409]
 [0.3868976  0.71044349 0.30339061]
 [0.18600618 0.14575841 0.80745898]]


In [ ]:
#Array properties
arr= np.array([[1,2,3,4],[2,3,4,5]])
print(arr)
#Shape or array
print (f'\ n The shape of the array is({arr.shape}')
#Size of array
print(f'The size of the array is({arr.size}')
#Datatype of array
print(f'The Data type of the array is({arr.dtype}')
#Dimensions of array
print(f'The Dimensions of the array is({arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
\ n The shape of the array is((2, 4)
The size of the array is(8
The Data type of the array is(int64
The Dimensions of the array is(2


In [ ]:
#Indexing and slicing
#Access the element in 1D Array
arr= np.array([1,2,3,4])
print(arr)
print(arr[3])
#slicing the elements
print (arr[0:3])
#Access the element in 2D Array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]


In [ ]:
print(arr2[1,1])

3


In [ ]:
print(arr2[0,:])#first row with all columns

[1 2 3]


In [ ]:
print(arr2[:,0])#first Column with all rows

[1 2]


In [ ]:
L1=[]
[L1.append(_) for _ in range (10)]
import numpy as np
L1=np.arange(10,-10,-3) # Assuming you intended 10 as the stop value, otherwise, change it accordingly
print (L1)

[10  7  4  1 -2 -5 -8]


In [33]:
#Mathematical  operator
a=np.array([1,2,3])
b=np.array([3,4,5])
print(f'The sum of a and b is{a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is[4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [34]:
#Matrix Multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])
#Dot.produt
c=np.dot(b1,b2)
print (c)

[[22 31]
 [35 48]]


In [35]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [36]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [38]:
[
[22,31],
 [35,48]
]

[[22, 31], [35, 48]]