<a href="https://colab.research.google.com/github/Amrinnridegreecollege/Python-mini-project-/blob/main/Interdution_to_Numpy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Recap
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#Dot product_mxn||nxp
arr1=np.random.randint(1,2,(3,1))

In [ ]:
arr.shape
arr1.shape

(3, 1)

In [ ]:
result=np.dot(arr,arr1)

In [ ]:
print(result)

[[ 6]
 [15]]


In [ ]:
r1=np.random.randint(10,20,(3,3))
print(r1)

[[16 10 13]
 [15 17 14]
 [13 18 12]]


In [ ]:
r2=np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#r1.I
result2=np.dot(r1,r2)

In [ ]:
print(result2)

[[16. 10. 13.]
 [15. 17. 14.]
 [13. 18. 12.]]


In [ ]:
#M.I=I.M=M

In [ ]:
#A.B!=B.A

In [ ]:
#Marhematical operations
#+-*/
t1=np.random.randint(3,6,(3,3))
t2=np.random.randint(3,6,(3,3))

In [ ]:
print (t1)

[[4 5 5]
 [3 3 5]
 [3 4 3]]


In [ ]:
print(t2)

[[5 3 4]
 [3 4 5]
 [3 5 5]]


In [ ]:
t3=t1*t2

In [ ]:
print(t3)

[[20 15 20]
 [ 9 12 25]
 [ 9 20 15]]


In [ ]:
#Matrix multiplication
result = np.dot(arr,arr1)

In [ ]:
#statistical operations
mean=t3.mean()
max=t3.max()
median=np.median(t3)
std=np.std(t3)
var=np.var(t3)

In [ ]:
print(median)

15.0


In [ ]:
print(std)

5.2163087085802236


In [ ]:
std*std

27.20987654320988

In [ ]:
#Trigonometric functions
#sin(x)
#cos(x)
#Tan(x)
#cos _1/sin(x)
#sec_1/cos(x)
#cot_1/tan(x)
#
angles=np.array([0,15,30,45,60,75,90])
#sin(array)
result=np.sin(np.radians(angles))

In [ ]:
print(result)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]


In [ ]:
arr=np.array([1,2,3,4,5,6])
#Reshape the array
reshapedarr=arr.reshape(3,2)
print(reshapedarr)
#Convert/Flatten any n dim array
flattenedarr =arr.flatten()
print(flattenedarr)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [32]:
#stacking the data
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

#vertical stacking
arr3=np.vstack((arr1,arr2))
print(f"The Shape of arr3 is{arr3.shape}")

#Horizontal stacking
arr4=np.hstack((arr1,arr2))
print(f"The shape of arr4 is{arr4.shape}")

The Shape of arr3 is(2, 4)
The shape of arr4 is(8,)


In [33]:
#Filtering
arr=np.array([10,20,30,40,50,60,70,80,90])
farr=arr[arr>40]
print(farr)

[50 60 70 80 90]
